export const FETCH_USERNAME = 'FETCH_USERNAME'
export const FETCH_EMAIL_ID = 'FETCH_EMAIL_ID'
export const FETCH_PASSWORD = 'FETCH_PASSWORD'
export const FETCH_MOBILE_NO = 'FETCH_MOBILE_NO'
export const FETCH_COUNTRY = 'FETCH_COUNTRY'
export const FETCH_PINCODE = 'FETCH_PINCODE'
export const FETCH_DESCRIPTION = 'FETCH_DESCRIPTION'


